return {
  "yetone/avante.nvim",
  event = "VeryLazy",
  version = false,
  opts = {
    provider = "claude",
    behaviour = {
      auto_set_keymaps = false,
    },
  },
  build = "make",
  dependencies = {
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    "ibhagwan/fzf-lua",
    {
      "HakonHarnes/img-clip.nvim",
      event = "VeryLazy",
      opts = {
        default = {
          embed_image_as_base64 = false,
          prompt_for_file_name = false,
          drag_and_drop = { insert_mode = true },
          use_absolute_path = true,
        },
      },
    },
    {
      "MeanderingProgrammer/render-markdown.nvim",
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
  cmd = {
    "AvanteAsk",
    "AvanteBuild",
    "AvanteChat",
    "AvanteClear",
    "AvanteEdit",
    "AvanteFocus",
    "AvanteHistory",
    "AvanteModels",
    "AvanteRefresh",
    "AvanteShowRepoMap",
    "AvanteStop",
    "AvanteSwitchProvider",
    "AvanteToggle",
  },
  keys = {
    { "<leader>va", "<cmd>AvanteAsk<CR>", desc = "Ask Avante" },
    { "<leader>vc", "<cmd>AvanteChat<CR>", desc = "Chat with Avante" },
    { "<leader>ve", "<cmd>AvanteEdit<CR>", desc = "Edit Avante" },
    { "<leader>vf", "<cmd>AvanteFocus<CR>", desc = "Focus Avante" },
    { "<leader>vh", "<cmd>AvanteHistory<CR>", desc = "Avante History" },
    { "<leader>vm", "<cmd>AvanteModels<CR>", desc = "Select Avante Model" },
    { "<leader>vn", "<cmd>AvanteChatNew<CR>", desc = "New Avante Chat" },
    { "<leader>vp", "<cmd>AvanteSwitchProvider<CR>", desc = "Switch Avante Provider" },
    { "<leader>vr", "<cmd>AvanteRefresh<CR>", desc = "Refresh Avante" },
    { "<leader>vs", "<cmd>AvanteStop<CR>", desc = "Stop Avante" },
    { "<leader>vt", "<cmd>AvanteToggle<CR>", desc = "Toggle Avante" },
  },
}
